In [8]:
import pandas as pd

In [14]:
compras_df = pd.read_excel("compras.xlsx")
display(compras_df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,9,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
93905,65012,2019-11-30,Shopping Vila Velha,Mochila Xadrez,2,283,566
93906,65013,2019-11-30,Ribeirão Shopping,Pulseira Listrado,2,79,158
93907,65013,2019-11-30,Ribeirão Shopping,Cueca Listrado,3,67,201
93908,65014,2019-11-30,Shopping Guararapes,Pulseira Linho,5,114,570
93909,65014,2019-11-30,Shopping Guararapes,Casaco Xadrez,4,259,1036

In [17]:
display(compras_df.head(15))

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,9,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
10,8,2019-01-02,Iguatemi Campinas,Terno Estampa,5,706,3530
11,9,2019-01-02,Shopping Center Leste Aricanduva,Tênis Linho,1,294,294
12,9,2019-01-02,Shopping Center Leste Aricanduva,Casaco Xadrez,9,259,518
13,10,2019-01-02,Passei das Águas Shopping,Camiseta Xadrez,9,200,400
14,10,2019-01-02,Passei das Águas Shopping,Cueca Liso,1,69,69

In [18]:
display(compras_df.head(15))
print(compras_df.shape)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,Iguatemi Esplanada,Sapato Estampa,1,358,358
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,9,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
10,8,2019-01-02,Iguatemi Campinas,Terno Estampa,5,706,3530
11,9,2019-01-02,Shopping Center Leste Aricanduva,Tênis Linho,1,294,294
12,9,2019-01-02,Shopping Center Leste Aricanduva,Casaco Xadrez,9,259,518
13,10,2019-01-02,Passei das Águas Shopping,Camiseta Xadrez,9,200,400
14,10,2019-01-02,Passei das Águas Shopping,Cueca Liso,1,69,69

(93910, 7)

In [19]:
produtos = compras_df[['Produto','ID Loja']]
display(produtos)

                 Produto              ID Loja
0         Sapato Estampa   Iguatemi Esplanada
1               Camiseta   Iguatemi Esplanada
2          Sapato Xadrez   Iguatemi Esplanada
3                Relógio       Norte Shopping
4           Chinelo Liso       Norte Shopping
...                  ...                  ...
93905     Mochila Xadrez  Shopping Vila Velha
93906  Pulseira Listrado    Ribeirão Shopping
93907     Cueca Listrado    Ribeirão Shopping
93908     Pulseira Linho  Shopping Guararapes
93909      Casaco Xadrez  Shopping Guararapes

[93910 rows x 2 columns]

In [20]:
# pegar uma linha 
display(compras_df.loc[1:15])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
1,1,2019-01-01,Iguatemi Esplanada,Camiseta,9,180,360
2,1,2019-01-01,Iguatemi Esplanada,Sapato Xadrez,1,368,368
3,2,2019-01-02,Norte Shopping,Relógio,3,200,600
4,2,2019-01-02,Norte Shopping,Chinelo Liso,1,71,71
5,3,2019-01-02,Rio Mar Shopping Fortaleza,Cinto Linho,1,248,248
6,5,2019-01-02,Shopping Barra,Calça,1,170,170
7,6,2019-01-02,Shopping Ibirapuera,Polo Listrado,4,149,596
8,7,2019-01-02,Norte Shopping,Camisa Gola V Listrado,1,116,116
9,7,2019-01-02,Norte Shopping,Camisa Liso,1,105,105
10,8,2019-01-02,Iguatemi Campinas,Terno Estampa,5,706,3530
11,9,2019-01-02,Shopping Center Leste Aricanduva,Tênis Linho,1,294,294
12,9,2019-01-02,Shopping Center Leste Aricanduva,Casaco Xadrez,9,259,518
13,10,2019-01-02,Passei das Águas Shopping,Camiseta Xadrez,9,200,400
14,10,2019-01-02,Passei das Águas Shopping,Cueca Liso,1,69,69
15,11,2019-01-02,Shopping Recife,Camiseta,1,180,180

In [21]:
# pegar uma linha ou coluna em uma condição especifica
# condição [linha,coluna]
print(compras_df.loc[10,'Produto'])

Terno Estampa

In [27]:
# pegar varias linhas e colunas usando o loc
compras_shopp_recife = compras_df.loc[compras_df['ID Loja'] == 'Shopping Recife',["ID Loja","Produto","Quantidade"]]
display(compras_shopp_recife)

               ID Loja         Produto  Quantidade
15     Shopping Recife        Camiseta           1
16     Shopping Recife  Calça Listrado           9
17     Shopping Recife  Camisa Estampa           1
61     Shopping Recife    Camisa Linho           1
122    Shopping Recife     Meia Xadrez           1
...                ...             ...         ...
93684  Shopping Recife  Camiseta Linho           1
93696  Shopping Recife     Terno Linho           2
93697  Shopping Recife           Terno           4
93698  Shopping Recife   Bermuda Linho           5
93765  Shopping Recife   Bermuda Linho           1

[3605 rows x 3 columns]